# Generated by Django 3.1.7 on 2021-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_books', to='p_library.Friend'),
        ),
    ]
