# Generated by Django 3.1.7 on 2021-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210504_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_books', to='p_library.Book'),
        ),
    ]
