# Generated by Django 3.1.7 on 2021-04-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210416_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redaction',
            old_name='title',
            new_name='name',
        ),
    ]
