# Generated by Django 3.1.7 on 2021-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AddField(
            model_name='author',
            name='photos',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='book',
            name='photos',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
