# Generated by Django 3.1.7 on 2021-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20210512_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photos',
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
